[package]
name = "day2"
version = "0.1.0"
authors = ["Alastair Harrison <aharrison24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
itertools = "0.9"
nom = "6.0"
